languageCode = "en-us"
title = "Melissa Del Bosque"
baseurl = "https://melissa-del-busque.netlify.com"
theme = "thenewdynamic-hugo-core-theme"

metaDataFormat = "yaml"
log = true
#SectionPagesMenu = "main"

[social]
twitter = "MelissaLaLinea"
#facebook = ""
#youtube = ""
#instagram = ""

[params]
  body_classes = "bg-white site-font"
  background_color_class = "bg-white"
  description = "hellow ro"

[taxonomies]
tag = "tags"
category = "categories"



[[menu.main]]
    name = "About Melissa"
    weight = 10
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "About the Book"
    identifier = "books"
    weight = 2
    url = "/book/bloodlines/"
[[menu.main]]
    name = "Articles"
    identifier = "writing"
    weight = 30
    url = "/writing/"


# [[menu.main]]
#     name = "contact"
#     identifier = "contact"
#     weight = 3
#     url = "/contact/"
# [[menu.main]]
#     name = "journal"
#     identifier = "journal"
#     weight = 4
#     url = "/journal/"
# [[menu.main]]
#     name = "events"
#     identifier = "events"
#     weight = 5
#     url = "/event/"
