languageCode = "en-us"
title = "Melissa del Bosque"
baseurl = "https://www.melissadelbosque.com"
theme = "thenewdynamic-hugo-core-theme"
googleAnalytics = "UA-105300766-1"
metaDataFormat = "yaml"
log = false
disableAliases = true
buildFuture = true
#SectionPagesMenu = "main"

[social]
twitter = "MelissaLaLinea"
#facebook = ""
#youtube = ""
#instagram = ""

[outputs]
  home = ["HTML", "RSS", "HEADERS", "REDIRECTS", "CSS"]

[mediaTypes]
[mediaTypes."text/netlify"]
  suffix = ""
  delimiter = ""

[outputFormats]
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true


[params]
  description = "Melissa del Bosque is an award-winning investigative journalist who has covered the U.S.-Mexico border region for the past two decades."

[params.styles]
  body_classes = "bg-white center site-font black mw9"
  color_classes = "black bg-white"
  background_color_class = "accent-color-dark"
  books_header_class = "dn"


[params.dev]
  js_path = "/static/dist/js"
  css_path = "/static/dist/css"

[taxonomies]
tag = "tags"
category = "categories"



# [[menu.main]]
#     name = "About Melissa"
#     weight = 10
#     identifier = "about"
#     url = "/about/"
[[menu.main]]
    name = "About Bloodlines"
    identifier = "books"
    weight = 2
    url = "/book/bloodlines/"
[[menu.main]]
    name = "Selected Works"
    identifier = "articles"
    weight = 30
    url = "/article/"


[[menu.main]]
    name = "About Melissa"
    identifier = "about"
    weight = 3
    url = "/about/"
# [[menu.main]]
#     name = "journal"
#     identifier = "journal"
#     weight = 4
#     url = "/journal/"
[[menu.main]]
    name = "Events"
    identifier = "events"
    weight = 5
    url = "/event/"
