languageCode = "en-us"
title = "Melissa Del Bosque"
baseurl = "https://melissa-del-bosque.netlify.com"
theme = "thenewdynamic-hugo-core-theme"

metaDataFormat = "yaml"
log = false
#SectionPagesMenu = "main"

[social]
twitter = "MelissaLaLinea"
#facebook = ""
#youtube = ""
#instagram = ""

[params]
  body_classes = "bg-white center sans-serif white mw9"
  color_classes = "black bg-white"
  description = "Melissa del Bosque is an award-winning investigative journalist who has covered the U.S.-Mexico border region for the past two decades."

[taxonomies]
tag = "tags"
category = "categories"



# [[menu.main]]
#     name = "About Melissa"
#     weight = 10
#     identifier = "about"
#     url = "/about/"
[[menu.main]]
    name = "About Bloodlines"
    identifier = "books"
    weight = 2
    url = "/book/bloodlines/"
[[menu.main]]
    name = "Articles"
    identifier = "articles"
    weight = 30
    url = "/article/"


# [[menu.main]]
#     name = "contact"
#     identifier = "contact"
#     weight = 3
#     url = "/contact/"
# [[menu.main]]
#     name = "journal"
#     identifier = "journal"
#     weight = 4
#     url = "/journal/"
# [[menu.main]]
#     name = "events"
#     identifier = "events"
#     weight = 5
#     url = "/event/"
