languageCode = "en-us"
title = "Melissa Del Bosque"
baseurl = ""
theme = "thenewdynamic-hugo-core-theme"
metaDataFormat = "yaml"
log = true
[params]
  body_classes = "bg-white serif"
  #background_color_class = "bg-near-black"

[taxonomies]
tag = "tags"
category = "categories"


[[menu.main]]
    name = "about"
    weight = 1
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "books"
    identifier = "books"
    weight = 2
    url = "/book/"
[[menu.main]]
    name = "contact"
    identifier = "contact"
    weight = 3
    url = "/contact/"
[[menu.main]]
    name = "journal"
    identifier = "journal"
    weight = 4
    url = "/journal/"
[[menu.main]]
    name = "events"
    identifier = "events"
    weight = 5
    url = "/event/"