---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
  review:
    default_front_matter_template: review
  event:
    default_front_matter_template: event
  book:
    default_front_matter_template: book
  article:
    default_front_matter_template: article
upload_dir: static/images
public_path: "/images"
front_matter_path: "/images"
use_front_matter_path: false
file_template: ":filename:"
version: '0.26'
