---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content/event
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - default
  - home
- type: document
  path: content/about.md
  label: About
  match: "**/*"
  templates:
  - default
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
